In [202]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error
from sklearn.neighbors import KNeighborsClassifier
plt.style.use("dark_background")


In [169]:
print(diabetes.keys())

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])


In [170]:
print(diabetes.data)

[[ 0.03807591  0.05068012  0.06169621 ... -0.00259226  0.01990842
  -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 ... -0.03949338 -0.06832974
  -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 ... -0.00259226  0.00286377
  -0.02593034]
 ...
 [ 0.04170844  0.05068012 -0.01590626 ... -0.01107952 -0.04687948
   0.01549073]
 [-0.04547248 -0.04464164  0.03906215 ...  0.02655962  0.04452837
  -0.02593034]
 [-0.04547248 -0.04464164 -0.0730303  ... -0.03949338 -0.00421986
   0.00306441]]


In [171]:
diabetes_x=diabetes.data

In [172]:
diabetes_x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [173]:
#Features for test and train
diabetes_x_train=diabetes.data[:-30]
diabetes_x_test=diabetes.data[-30:]

In [174]:
#labels for test and train
diabetes_y_train=diabetes.target[:-30]
diabetes_y_test=diabetes.target[-30:]

In [175]:
model = linear_model.LinearRegression()

In [176]:
model.fit(diabetes_x_train,diabetes_y_train)

LinearRegression()

In [177]:
diabetes_y_predicted=model.predict(diabetes_x_test)

In [178]:
print("Mean squared error is ", mean_squared_error(diabetes_y_test,diabetes_y_predicted))

Mean squared error is  1826.5364191345423


In [179]:
print("Weights: ",model.coef_)

Weights:  [  -1.16924976 -237.18461486  518.30606657  309.04865826 -763.14121622
  458.90999325   80.62441437  174.32183366  721.49712065   79.19307944]


In [180]:
print("Interceptor: ", model.intercept_)

Interceptor:  153.05827988224112


In [181]:
diabetes.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

In [182]:
diabetes.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

# Impoerting iris dataset
data_iris=datasets.load_iris()

In [184]:
data_iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [185]:
#set train and test data set of features and labels 
data_iris_x_train=data_iris.data[:-50]
data_iris_x_test=data_iris.data[-50:]
data_iris_y_train=data_iris.target[:-50]
data_iris_y_test=data_iris.target[-50:]

In [189]:
#linear regresion on iris dataset
model_iris= linear_model.LinearRegression()

In [190]:
model_iris.fit(data_iris_x_train,data_iris_y_train)

LinearRegression()

In [191]:
#predicted the ;labels of given features
test_data_predict=model_iris.predict(data_iris_x_test)

In [198]:
#error
mean_squared_error(data_iris_y_test,test_data_predict)

0.3833330368638276

In [199]:
#Weights of model_iris
model.coef_

array([  -1.16924976, -237.18461486,  518.30606657,  309.04865826,
       -763.14121622,  458.90999325,   80.62441437,  174.32183366,
        721.49712065,   79.19307944])

In [201]:
#Interceptor of model_iris
model_iris.intercept_

0.369703423280362

In [203]:
iris2=datasets.load_iris()

In [206]:
iris2.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [207]:
iris2.target[0]

0

In [208]:
iris2.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =

In [209]:
features=iris2.data

In [210]:
labels=iris2.target

In [211]:
clf= KNeighborsClassifier()

In [214]:
model2=clf.fit(features,labels)

In [238]:
prd=model2.predict([[5.9, 3. ,0, 1.8]])

In [235]:
prd

array([0])

In [217]:
iris2.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [219]:
iris2.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [230]:
iris2.data[149]

array([5.9, 3. , 5.1, 1.8])

In [228]:
iris2.target[149]

2